apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: voting-app
resources:
  - namespace.yml
  - postgres-pvc.yml
  - postgres-pv.yml
  - db.yml
  - redis.yml
  - worker.yml
  - vote.yml
  - result.yml