apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: ghenac/voting-app-worker:v2
        imagePullPolicy: IfNotPresent
        env:
          - name: DB_HOST
            value: "db-svc"
          - name: DB_USERNAME
            value: "postgres"
          - name: DB_PASSWORD
            value: "postgres"
          - name: DB_NAME
            value: "postgres"
          - name: REDIS_HOST
            value: "redis-svc"

---
apiVersion: v1
kind: Service
metadata:
  name: worker-svc
  namespace: voting-app
spec:
  selector:
    app: worker
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP


