---
#####--------------------------------------------------- Play 1: Docker Installation ---------------------------------------------------#####

- name: Ensure Docker is installed and running on the 'backend' instance
  hosts: backend
  become: yes
  vars:
    postgres_password: "postgres"
    postgres_db: "voting_app_db"
    postgres_user: "voting_user"
    postgres_port: 5432
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes


    - name: Install Docker if not present
      package:
        name: docker.io
        state: present

    - name: Add the user to the Docker group
      ansible.builtin.user:
        name: "ubuntu"
        groups: docker
        append: yes
        state: present

    - name: Ensure Docker network "backend-network" exists
      docker_network:
        name: backend-network
        state: present
      ignore_errors: true

#####--------------------------------------------------- Play 2: Running "Redis" and "Worker" Containers ---------------------------------------------------#####

- name: Running "Redis" and "Worker" Containers
  hosts: backend
  become: yes
  tasks:
    ##### Redis Service #####
    - name: Pull the 'Redis' Docker image
      ansible.builtin.docker_image:
        name: redis:alpine
        source: pull
        
    - name: Check if port 6379 is in use
      shell: |
        lsof -i :6379 | grep -v COMMAND | awk '{print $2}' || echo ""
      register: port_check
      changed_when: port_check.stdout != ""
      ignore_errors: true

    - name: Kill process using port 6379 (if any)
      shell: |
        PID=$(lsof -ti :6379)
        if [ -n "$PID" ]; then
          kill -9 $PID
        fi
      register: kill_output
      failed_when: false
      changed_when: kill_output.stdout != ""

    - name: Stop all running containers that use port 6379
      docker_container:
        name: "{{ item }}"
        state: stopped
      loop: "{{ lookup('docker_container', '', True).splitlines() }}"
      when: item.ports is defined and '6379/tcp' in item.ports
      failed_when: false
      ignore_errors: true

    - name: Wait for port 6379 to be free
      wait_for:
        host: 10.0.2.150
        port: 6379
        state: stopped
        timeout: 10
      when: port_check.stdout != ""

    - name: Run the 'Redis' container
      ansible.builtin.docker_container:
        name: redis
        image: redis:alpine
        state: started
        networks:
          - name: backend-network
        restart_policy: always
        exposed_ports:
          - "6379"
        published_ports:
          - "6379:6379"
      when: port_check.stdout == ""
      failed_when: false

    - name: Verify the 'Redis' container is running
      ansible.builtin.docker_container_info:
        name: redis
      register: redis_container_info

    ##### Worker Service #####
    - name: Pull the 'worker' Docker image
      ansible.builtin.docker_image:
        name: ghenac/voting-app-worker
        tag: latest
        source: pull

    - name: Run the 'worker' container
      ansible.builtin.docker_container:
        name: voting-app-worker
        image: ghenac/voting-app-worker:latest
        state: started
        networks:
          - name: backend-network
        restart_policy: always
        env:
          REDIS_HOST: "redis"  # This is how the worker will connect to Redis container by using the container name as hostname
          REDIS_PORT: "6379"
          DB_HOST: "10.0.2.174"
          DB_USERNAME: "postgres"
          DB_PASSWORD: "postgres"
          DB_NAME: "voting-app-db"
      
        volumes:
          - /tmp:/tmp

    - name: Verify the worker container is running
      ansible.builtin.docker_container_info:
        name: voting-app-worker
      register: worker_container_info