---
- name: Ensure Docker is installed and running on the backend instance
  hosts: backend
  become: yes
  tasks:
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker if not installed
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Create backend Docker network if it does not exist
      ansible.builtin.docker_network:
        name: backend-network
        state: present

    - name: Add the user to the Docker group
      ansible.builtin.user:
        name: "ubuntu"
        groups: docker
        append: yes
        state: present

    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    ##### Redis Service #####
    - name: Pull the Redis Docker image
      ansible.builtin.docker_image:
        name: redis:alpine
        source: pull

    - name: Run the Redis container
      ansible.builtin.docker_container:
        name: Redis
        image: redis:alpine
        state: started
        networks:
          - name: backend-network
        restart_policy: always
        exposed_ports:
          - "6379"
        published_ports:
          - "6379:6379"

    - name: Verify the Redis container is running
      ansible.builtin.docker_container_info:
        name: Redis
      register: redis_container_info


    ##### Worker Service #####
    - name: Pull the worker Docker image
      ansible.builtin.docker_image:
        name: ghenac/voting-app-worker
        tag: latest
        source: pull

    - name: Run the worker-app container
      ansible.builtin.docker_container:
        name: voting-app-worker
        image: ghenac/voting-app-worker:latest
        state: started
        networks:
          - name: backend-network
        restart_policy: always
        env:
          REDIS_HOST: "Redis"  # This is how the worker will connect to Redis container by using the container name as hostname
          REDIS_PORT: "6379"
          DB_HOST: "10.0.2.174"
          DB_USERNAME: "postgres"
          DB_PASSWORD: "postgres"
          DB_NAME: "voting-app-db"
      
        volumes:
          - /tmp:/tmp

    - name: Verify the worker container is running
      ansible.builtin.docker_container_info:
        name: voting-app-worker
      register: worker_container_info