---
#####--------------------------------------------------- Play 1: Docker Installation ---------------------------------------------------#####

- name: Ensure Docker is installed and running on the 'DB' instance
  hosts: db
  become: yes
  vars:
    postgres_password: "postgres"
    postgres_db: "voting_app_db"
    postgres_user: "voting_user"
    postgres_port: 5432
  tasks:
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker if not present
      package:
        name: docker.io
        state: present

    - name: Add the user to the Docker group
      ansible.builtin.user:
        name: "ubuntu"
        groups: docker
        append: yes
        state: present

    - name: Ensure Docker network "voting-app-network" exists
      ansible.builtin.command:
        cmd: docker network create voting-app-network
      register: docker_network_creation
      failed_when: docker_network_creation.stderr != ""
      ignore_errors: true

#####--------------------------------------------------- Play 2: Running "DB" Container ---------------------------------------------------#####

- name: Running "DB" Container
  hosts: db
  become: yes
  tasks:
    ##### DB service #####
    - name: Pull the 'PostgreSQL' Docker image
      community.docker.docker_image:
        name: postgres:15-alpine
        source: pull

    - name: Run the 'PostgreSQL' container
      community.docker.docker_container:
        name: voting-app-db
        image: postgres:15-alpine
        state: started
        restart_policy: always
        env:
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_DB: "voting-app-db"
          POSTGRES_USER: "postgres"
        exposed_ports:
          - "5432"
        published_ports:
          - "5432:5432"
        networks:
          - name: voting-app-network
        volumes:
          - name: pgdata
            source: pgdata
            target: /var/lib/postgresql/data
            type: volume
            state: present

    - name: Verify the PostgreSQL container is running
      community.docker.docker_container_info:
        name: voting-app-db
      register: container_info

    - name: Debug container information
      debug:
        var: container_info
