---
#####--------------------------------------------------- Play 1: Docker Installation ---------------------------------------------------#####

- name: Ensure Docker is installed and running on the 'DB' instance
  hosts: db
  become: yes
  vars:
    postgres_password: "postgres"
    postgres_db: "voting_app_db"
    postgres_user: "voting_user"
    postgres_port: 5432
  tasks:
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Remove conflicting containerd packages (if any)
      ansible.builtin.apt:
        name: containerd
        state: absent

    - name: Install Docker dependencies
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker's GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /usr/share/keyrings/docker-archive-keyring.gpg
      notify: Update apt-key

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present


    - name: Update apt package index (after adding Docker repository)
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker CE
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Add the user to the Docker group
      ansible.builtin.user:
        name: "ubuntu"
        groups: docker
        append: yes
        state: present

    - name: Ensure Docker service is running and enabled
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Ensure Docker network "voting_app_network" exists
      ansible.builtin.command:
        cmd: docker network create voting_app_network
      register: docker_network_creation
      failed_when: docker_network_creation.stderr != ""
      ignore_errors: true

#####--------------------------------------------------- Play 2: Running "DB" Container ---------------------------------------------------#####

- name: Running "DB" Container
  hosts: db
  become: yes
  tasks:
    ##### DB service #####
    - name: Pull the 'PostgreSQL' Docker image
      community.docker.docker_image:
        name: postgres:15-alpine
        source: pull

    - name: Run the 'PostgreSQL' container
      community.docker.docker_container:
        name: voting-app-db
        image: postgres:15-alpine
        state: started
        restart_policy: always
        env:
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_DB: "voting-app-db"
          POSTGRES_USER: "postgres"
        exposed_ports:
          - "5432"
        published_ports:
          - "5432:5432"
        networks:
          - name: voting_app_network
        volumes:
          - name: pgdata
            source: pgdata
            target: /var/lib/postgresql/data
            type: volume
            state: present

    - name: Verify the PostgreSQL container is running
      community.docker.docker_container_info:
        name: voting-app-db
      register: container_info

    - name: Debug container information
      debug:
        var: container_info
