---
- name: Ensure Docker is installed and running on the frontend instance
  hosts: frontend
  become: yes
  tasks:
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker if not installed
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

##### Vote Service #####
    - name: Pull the vote Docker image
      ansible.builtin.docker_image:
        name: ghenac/voting-app
        tag: vote
        source: pull

    - name: Run the 'vote' container
      ansible.builtin.docker_container:
        name: voting-app-vote
        image: ghenac/voting-app:vote
        state: started
        restart_policy: always
        exposed_ports:
          - "80"
        published_ports:
          - "8080:80"

    - name: Verify the container is running
      ansible.builtin.docker_container_info:
        name: voting-app-vote
      register: container_info

    
##### Result Service #####
- name: Ensure Docker is installed and running on the vote instance
  hosts: frontend
  become: yes
  tasks:
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker if not installed
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Pull the result Docker image
      ansible.builtin.docker_image:
        name: ghenac/voting-app
        tag: result
        source: pull

    - name: Run the 'result' container
      ansible.builtin.docker_container:
        name: voting-app-result
        image: ghenac/voting-app:result
        state: started
        restart_policy: always
        exposed_ports:
          - "80"
        published_ports:
          - "8081:80"

    - name: Verify the container is running
      ansible.builtin.docker_container_info:
        name: voting-app-result
      register: container_info