all:
  children:
    db:
      hosts:
        db-instance:
          ansible_host: 10.0.2.174
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/ubuntu/voting-app-key.pem  # On the frontend EC2
    backend:
      hosts:
        backend-instance:
          ansible_host: 10.0.2.150
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/ubuntu/voting-app-key.pem
    frontend:
      hosts:
        localhost:
          ansible_connection: local

